version: '3.7'
services: 
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapi'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  database:
    image: mysql:5.7
    restart: always
    ports: 
      - "3305:3306"
    environment:
      MYSQL_DATABASE: 'laraapp_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql